cameras:
  testsrc:
    local_command: ffmpeg -hide_banner -loglevel error -f lavfi -i testsrc=size=640x480:rate=1 -frames:v 1 -f image2pipe -vcodec mjpeg -
    lat: 37.6
    lon: -122.4
    timeout_s: 20
    snap_interval_s: 5
    postprocessing:
      - type: resize
        height: 240
      - type: timestamp
        enabled: true
        size: 16
        color: white
        background_color: "(40, 40, 40)"
      - type: gather_metrics
        enabled: true
    ssim_area: 0,0,640,120
    ssim_setpoint: 0.9

global:
  timezone: UTC
  work_dir: /tmp/fenetre-smaller/data
  log_dir: /tmp/fenetre-smaller/logs
  storage_management:
    enabled: false

http_server:
  enabled: false

admin_server:
  enabled: false

timelapse: {}
