[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fenetre"
version = "1.1.0"
dependencies = [
    "pytz",
    "pyyaml>=6.0.1",
    "absl-py",
    "numpy",
    "astral",
    "Flask>=3.0.3",
    "Werkzeug>=3.0.3",
    "requests>=2.32.0",
    "mozjpeg-lossless-optimization",
    "paho-mqtt",
    "waitress>=3.0.0",
    "prometheus-client",
    "scikit-image",
    "Pillow>=10.3.0",
    "cairosvg",
    "piexif",
]

[project.optional-dependencies]
dev = [
    "black",
    "pytest",
]
gopro = [
    "bleak",
    "beautifulsoup4",
    "netifaces",
]
picamera2 = [
    "picamera2",
]
pyexiv2 = [
    "pyexiv2",
]
ptz = [
    "onvif-zeep",
]

[project.scripts]
fenetre = "fenetre.compat:run"
fenetre-user = "fenetre.auth:main"
daylight-tool = "fenetre.daylight_tool:run"
timelapse-tool = "fenetre.timelapse_tool:run"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["fenetre"]

[tool.flake8]
max-line-length = 120
ignore = "E501"

[tool.isort]
profile = "black"
line_length = 120
